apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-helloworld
  labels:
    app: go-helloworld
  name: go-helloworld
  namespace: uda-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-helloworld
    spec:
      containers:
      - name: go-helloworld
        image: sakuffo/go-helloworld:v2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6112
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 6112
        readinessProbe:
          httpGet:
            path: /
            port: 6112
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
