apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-helloworld
  name: go-helloworld
  namespace: uda-demo
spec:
  selector:
    app: go-helloworld
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 6112
  type: ClusterIP
